# Generated by Django 5.0.6 on 2024-11-12 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devicelogs',
            fields=[
                ('devicelogid', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('downloaddate', models.DateTimeField(blank=True, db_column='DownloadDate', null=True)),
                ('devicename', models.CharField(blank=True, db_column='devicename', max_length=255, null=True)),
                ('userid', models.CharField(db_column='EmpCode', max_length=50)),
                ('logdate', models.DateTimeField(db_column='datetime')),
                ('direction', models.CharField(blank=True, db_column='direction', max_length=255, null=True)),
                ('serialnumber', models.CharField(blank=True, db_column='serianumber', max_length=255, null=True)),
                ('attdirection', models.CharField(blank=True, db_column='AttDirection', max_length=255, null=True)),
                ('c1', models.CharField(blank=True, db_column='C1', max_length=255, null=True)),
                ('c2', models.CharField(blank=True, db_column='C2', max_length=255, null=True)),
                ('c3', models.CharField(blank=True, db_column='C3', max_length=255, null=True)),
                ('c4', models.CharField(blank=True, db_column='C4', max_length=255, null=True)),
                ('c5', models.CharField(blank=True, db_column='C5', max_length=255, null=True)),
                ('c6', models.CharField(blank=True, db_column='C6', max_length=255, null=True)),
                ('c7', models.CharField(blank=True, db_column='C7', max_length=255, null=True)),
                ('workcode', models.CharField(blank=True, db_column='WorkCode', max_length=255, null=True)),
            ],
            options={
                'db_table': 'raw',
                'ordering': ['-logdate'],
            },
        ),
        migrations.CreateModel(
            name='LocalDevicelogs',
            fields=[
                ('devicelogid', models.AutoField(db_column='DeviceLogId', primary_key=True, serialize=False)),
                ('downloaddate', models.DateTimeField(blank=True, db_column='DownloadDate', null=True)),
                ('deviceid', models.IntegerField(db_column='DeviceId')),
                ('userid', models.CharField(db_column='UserId', max_length=50)),
                ('logdate', models.DateTimeField(db_column='LogDate')),
                ('direction', models.CharField(blank=True, db_column='Direction', max_length=255, null=True)),
                ('attdirection', models.CharField(blank=True, db_column='AttDirection', max_length=255, null=True)),
                ('c1', models.CharField(blank=True, db_column='C1', max_length=255, null=True)),
                ('c2', models.CharField(blank=True, db_column='C2', max_length=255, null=True)),
                ('c3', models.CharField(blank=True, db_column='C3', max_length=255, null=True)),
                ('c4', models.CharField(blank=True, db_column='C4', max_length=255, null=True)),
                ('c5', models.CharField(blank=True, db_column='C5', max_length=255, null=True)),
                ('c6', models.CharField(blank=True, db_column='C6', max_length=255, null=True)),
                ('c7', models.CharField(blank=True, db_column='C7', max_length=255, null=True)),
                ('workcode', models.CharField(blank=True, db_column='WorkCode', max_length=255, null=True)),
            ],
            options={
                'db_table': 'LocalDeviceLogs',
                'ordering': ['-logdate'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('intime', models.DateTimeField(blank=True, null=True)),
                ('intime_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('outtime', models.DateTimeField(blank=True, null=True)),
                ('outtime_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('total_working_hours', models.FloatField(blank=True, default=0, null=True)),
                ('p1', models.DateTimeField(blank=True, null=True)),
                ('p1_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p2', models.DateTimeField(blank=True, null=True)),
                ('p2_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p3', models.DateTimeField(blank=True, null=True)),
                ('p3_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p4', models.DateTimeField(blank=True, null=True)),
                ('p4_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p5', models.DateTimeField(blank=True, null=True)),
                ('p5_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p6', models.DateTimeField(blank=True, null=True)),
                ('p6_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p7', models.DateTimeField(blank=True, null=True)),
                ('p7_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p8', models.DateTimeField(blank=True, null=True)),
                ('p8_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p9', models.DateTimeField(blank=True, null=True)),
                ('p9_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p10', models.DateTimeField(blank=True, null=True)),
                ('p10_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('adjustment', models.BooleanField(default=False)),
                ('adjustment_count', models.IntegerField(default=0)),
                ('ot_hours', models.FloatField(blank=True, default=0, null=True)),
                ('absent', models.CharField(blank=True, choices=[('AB', 'AB'), ('P', 'P')], max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=4, null=True)),
                ('is_manual_edit', models.BooleanField(blank=True, default=False, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_employee', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_employee_per_day'),
        ),
    ]
