# Generated by Django 5.0.6 on 2024-11-12 12:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hours', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('relieving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.category')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Employee Code')),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Name')),
                ('employee_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Employee Mobile')),
                ('emergency_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Mobile')),
                ('father_or_husband_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Father or Husband Name')),
                ('address_1', models.TextField(blank=True, null=True, verbose_name='Address Line 1')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pincode')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('qualification', models.CharField(blank=True, choices=[('10thbelow', '10th Below'), ('10th', '10th'), ('12th', '12th'), ('ug', 'UG'), ('pg', 'pg'), ('diplamo', 'Diplamo')], max_length=100, null=True, verbose_name='Qualification')),
                ('marital_status', models.CharField(blank=True, choices=[('unmarried', 'Unmarried'), ('married', 'Married')], max_length=100, null=True, verbose_name='Marital Status')),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Blood Group')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=100, null=True, verbose_name='Gender')),
                ('weekly_off', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100, null=True, verbose_name='Weekly Off')),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('date_of_re_joining', models.DateField(blank=True, null=True, verbose_name='Date of Re-joining')),
                ('date_of_leaving', models.DateField(blank=True, null=True, verbose_name='Date of Leaving')),
                ('pf_esi_applicable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10, verbose_name='PF/ESI Applicable')),
                ('pf_date_of_joining', models.DateField(blank=True, null=True, verbose_name='PF Date of Joining')),
                ('pf_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='PF Number')),
                ('esi_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ESI Number')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name')),
                ('account_holder', models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Holder')),
                ('account_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='IFSC Code')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch')),
                ('nominee_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nominee Name')),
                ('nominee_relationship', models.CharField(blank=True, choices=[('mother', 'mother'), ('father', 'father'), ('son', 'son'), ('daughter', 'daughter'), ('spouse', 'spouse'), ('husband', 'husband'), ('guardian', 'guardian')], max_length=100, null=True, verbose_name='Nominee Relationship')),
                ('nominee_age', models.IntegerField(blank=True, null=True, verbose_name='Nominee Age')),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Employee Photo')),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Aadhar Number')),
                ('migrant_worker', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20, null=True, verbose_name='Migrant Worker')),
                ('migrant_worker_specific', models.CharField(blank=True, choices=[('tamil', 'tamil'), ('hindi', 'hindi'), ('tamil-worker', 'tamil-worker'), ('hindi-worker', 'hindi-worker'), ('malayalam', 'malayalam'), ('telugu', 'telugu'), ('kannadam', 'kannadam')], default='tamil', max_length=20, null=True, verbose_name='Migrant Worker Specific')),
                ('food_expense', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20, null=True, verbose_name='Food Expense')),
                ('working_mode', models.CharField(blank=True, choices=[('dayscholar', 'Day Scholar'), ('hostel', 'Hostel'), ('outsideworkers', 'Outside Workers')], default='dayscholar', max_length=40, null=True, verbose_name='Working Mode')),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending')], default='active', max_length=100, null=True, verbose_name='Status')),
                ('ot_available', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100, null=True, verbose_name='OT Applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('pf_percentage', models.FloatField(blank=True, default=12.0, null=True, verbose_name='PF Percentage')),
                ('esi_percentage', models.FloatField(blank=True, default=0.75, null=True, verbose_name='ESI Percentage')),
                ('pf_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='PF Amount')),
                ('esi_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='ESI Amount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_by_designation', to='employee.designation', verbose_name='Designation')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissioned_employees', to='employee.leader')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deduction_type', models.CharField(choices=[('advance', 'Advance'), ('mess', 'Mess'), ('store', 'Store'), ('others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('incentive_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Incentive Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_incentives', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderCommissionWages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_wages', to='employee.leader')),
            ],
        ),
        migrations.CreateModel(
            name='Wages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day', models.IntegerField(blank=True, default=0, null=True, verbose_name='Wages/Day')),
                ('basic_precentage', models.IntegerField(blank=True, default=60, null=True, verbose_name='BASIC %')),
                ('da_precentage', models.IntegerField(blank=True, default=40, null=True, verbose_name='DA %')),
                ('hra_precentage', models.IntegerField(blank=True, default=0, null=True, verbose_name='HRA  %')),
                ('other_allowance_precentage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Other allowance %')),
                ('basic_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='BASIC')),
                ('da_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name=' DA')),
                ('hra_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='HRA')),
                ('other_allowance', models.IntegerField(blank=True, default=0, null=True, verbose_name='Other allowance')),
                ('rent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rent')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_wages', to='employee.employee')),
            ],
        ),
    ]
