# Generated by Django 5.0.6 on 2024-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nominee_relationship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nominee Relationship'),
        ),
    ]
