# Generated by Django 5.0.6 on 2024-11-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_nominee_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marital Status'),
        ),
    ]
