# Generated by Django 5.0.6 on 2024-12-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDaysAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('department_name', models.CharField(max_length=255)),
                ('total_employees', models.IntegerField(default=0)),
                ('extra_days_worked', models.IntegerField(default=0)),
                ('incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ot_hours', models.IntegerField(default=0)),
                ('ot_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
