# Generated by Django 5.0.6 on 2024-12-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_extradaysabstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPFAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('department_name', models.CharField(max_length=255)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_paid_days', models.IntegerField(default=0)),
                ('total_ot_hours', models.IntegerField(default=0)),
                ('ot_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('shift_wages', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('per_day_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('canteen_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mess_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('store_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
