# Generated by Django 5.0.6 on 2024-11-12 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('WH', 'Weekly Holiday'), ('NH', 'National Holiday'), ('FH', 'Festival Holiday')], max_length=20)),
                ('festival_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AuditAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('intime', models.DateTimeField(blank=True, null=True)),
                ('intime_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('outtime', models.DateTimeField(blank=True, null=True)),
                ('outtime_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('total_working_hours', models.FloatField(blank=True, default=0, null=True)),
                ('p1', models.DateTimeField(blank=True, null=True)),
                ('p1_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p2', models.DateTimeField(blank=True, null=True)),
                ('p2_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p3', models.DateTimeField(blank=True, null=True)),
                ('p3_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p4', models.DateTimeField(blank=True, null=True)),
                ('p4_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p5', models.DateTimeField(blank=True, null=True)),
                ('p5_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p6', models.DateTimeField(blank=True, null=True)),
                ('p6_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p7', models.DateTimeField(blank=True, null=True)),
                ('p7_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p8', models.DateTimeField(blank=True, null=True)),
                ('p8_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p9', models.DateTimeField(blank=True, null=True)),
                ('p9_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('p10', models.DateTimeField(blank=True, null=True)),
                ('p10_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('adjustment', models.BooleanField(default=False)),
                ('adjustment_count', models.IntegerField(default=0)),
                ('ot_hours', models.FloatField(blank=True, default=0, null=True)),
                ('absent', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=4, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_attendance_employee', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Audit Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='WeekOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], max_length=20)),
                ('employee_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekoff_employee', to='employee.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='auditattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_audit_attendance_per_employee_per_day'),
        ),
    ]
