# Generated by Django 5.0.6 on 2024-12-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('department_name', models.CharField(max_length=255)),
                ('total_employees', models.IntegerField(default=0)),
                ('shift_wages', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_per_day_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_ot_hours', models.IntegerField(default=0)),
                ('total_basic_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_da_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_hra_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_pf_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_esi_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_paid_days', models.IntegerField(default=0)),
                ('advance_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mess_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('store_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('others_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_salary_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
